

# site icon
favicon: /favicon.png

# author headimg
headimg: /favicon.png

# search
search: 
    enable: true
    placeholder: Enter Key...

# sidebar
sidebar: 
  enable: true
  menus:
    -
      name: Home
      link: /
      target: _self
    -
      name: Category
      link: /category
      target: _self
    -
      name: Archive
      link: /archives
      target: _self
    -
      name: Tag
      link: /
      target: _self

# count(统计)
count:
  enable: true

# commen  ts
comments:
  #duoshuo_username:  yumemor
  disqus_username: huifeidmeng

# accounts support weibo/github/zhihu/twitter/douban 
# display to former three
social: 
  -
    name: weibo
    link: http://weibo.com/3879883747/
  -
    name: github
    link: /
  -
    name: weixin
    link: /
#  -
#    name: twitter
#    link: 
#  -
#    name: douban
#    link: 





